export const Project = [
  {
    projectName: "Mroc",
    type: "Side project & UI design assistant",
    status: "On going",
    timeRanges: "Mar 2023 - Present",
    siteLink: "https://mroc.netlify.app/",
    projectSummary:
      "Advance information research tools with strong in both qualitative and quantitative research methods.",
    summary:
      "I aim to enhance my coding proficiency by actively participating in the redesign process of our company's software using the React framework, encompassing both the front-end and back-end development aspects.",
    frontendStack: [
      "React",
      "React Query",
      "React Beautiful DnD",
      "Ant Design (antd)",
      "Axios",
      "Chart.js",
      "Dayjs",
      "Lodash",
      "React Router DOM",
      "Zustand",
      "Tailwind CSS",
      "TypeScript",
      "Vite",
    ],
    backendStack: [
      "Prisma",
      "SendGrid",
      "bcrypt",
      "Express",
      "JWT",
      "Cockroach db",
    ],
  },
  {
    projectName: "Meenites",
    type: "Side project",
    status: "On going",
    timeRanges: "Aug 2023 - Present",
    // siteLink: "https://mroc.netlify.app/",
    projectSummary: "Personal classroom management for teachers and students",
    summary:
      "This application empowers freelance teachers to effortlessly manage their classroom schedules and create online meeting links for students. Students can conveniently access their timetables and join virtual classes, streamlining the online learning experience.",
    frontendStack: [
      "Next.js",
      "React Query",
      "Ant Design (antd)",
      "Axios",
      "Dayjs",
      "Lodash",
      "Zustand",
      "Tailwind CSS",
      "TypeScript",
      "Zod",
      "Nextauth.js",
    ],
    backendStack: [
      "Prisma",
      "bcrypt",
      "Next.js api route",
      "JWT",
      "Supabase",
      "Googleapis",
      "Line messaging API",
    ],
  },
];
